name: CI-docs
on:
  push:
    branches: ['master', 'github_actions_ci']
    paths: ['docs/**', 'examples/**']
  pull_request:
    branches: ['master', 'github_actions_ci']
    paths: ['docs/**', 'examples/**']

jobs:

  docs:
    runs-on: ubuntu-24.04

    steps:

    - name: Git checkout with submodules
      uses: actions/checkout@v4.1.1
      with:
        submodules: true

    - name: Install dependencies
      run: |
        docs/build_docs.sh --install-deps --skip-build

    - name: Build docs
      run: |
        docs/build_docs.sh
