name: CI
on:
  push:
    paths: [ cmake/projects/** ]
  pull_request:
    paths: [ cmake/projects/** ]

jobs:

  set_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:

    - name: Git checkout
      uses: actions/checkout@v2

    - name: Get changed files and save them to ${HOME}/files.json
      id: files
      uses: lots0logs/gh-action-get-changed-files@2.1.4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set matrix for subsequent build
      id: set-matrix
      run: |
        echo "::set-output name=matrix::`python .github/workflows/set_matrix.py`"

  build:
    needs: set_matrix
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.set_matrix.outputs.matrix) }}

    env:
      TOOLCHAIN: ${{ matrix.toolchain }}
      PROJECT_DIR: examples/${{ matrix.example }}

    steps:

    - name: Git checkout with submodules
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Build on Unix
      if: "!startsWith(matrix.os, 'windows')"
      run: |
        bash ${{ matrix.script }}

    - name: Build on Windows
      if: "startsWith(matrix.os, 'windows')"
      run: |
        ${{ matrix.script }}